steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/director:$COMMIT_SHA', '-f', 'Dockerfile', '--build-arg', 'COMMIT_SHA=$COMMIT_SHA', '.']
images:
- 'gcr.io/$PROJECT_ID/director:$COMMIT_SHA'
