apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    project: {{ .Values.name }}
spec:
  selector:
    project: {{ .Values.name }}
  ports:
    {{- range $k, $v := .Values.ports }}
    -
      name: {{ $k }}
      port: {{ $v }}
      targetPort: {{ $k }}
    {{- end }}
  type: LoadBalancer
