apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: director
  labels:
    project: director
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: director
  serviceName: director
  template:
    metadata:
      labels:
        project: director
    spec:
      containers:
      - name: director
        image: "{{ .Values.image.repository }}@{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value}}
        {{- end }}
        volumeMounts:
          - name: ssl-certificates
            mountPath: /etc/director/certificates
        ports:
        {{- range $k, $v := .Values.ports }}
        - name: {{ $k }}
          containerPort: {{ $v }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: ssl-certificates
          persistentVolumeClaim:
            claimName: ssl-certificates
