apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: director
  labels:
    project: director
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: director
      role: app-server
  template:
    metadata:
      labels:
        project: director
        role: app-server
    spec:
      containers:
      - name: director
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: "UPSTREAM_HOST"
          value: "support.zd-dev.com"
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
