apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: director
  labels:
    project: director
spec:
  replicas: 1
  selector:
    matchLabels:
      project: director
      role: app-server
  template:
    metadata:
      labels:
        project: director
        role: app-server
    spec:
      containers:
      - name: director
        image: gcr.io/project-1804904848208322692/github-dndungu-director:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
