apiVersion: v1
kind: Service
metadata:
  name: facade
  labels:
    project: facade
spec:
  selector:
    project: facade
    role: app-server
  ports:
    -
      name: http
      port: 80
      targetPort: http
    -
      name: https
      port: 443
      targetPort: https
  type: LoadBalancer
