replicaCount: 1
image:
  repository: dndungu/director
  tag: sha256:facc95981782d7d6ba1c93997230309fb2d686be4f9c34b6c19d2ee1808830be
  pullPolicy: Always
name: director
env:
  target_host:
    name: "TARGET_HOST"
    value: "nginx"
ports:
  http: 80
  https: 443
resources:
  limits:
    cpu: 200m
    memory: 1024Mi
